version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_app
    command: -p 1221   # установка порта, отличного от стандартного
    expose:
      - 1221   # установка порта, отличного от стандартного
    env_file:
      - .env-non-dev

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370   # установка порта, отличного от стандартного
    expose:
      - 5370   # установка порта, отличного от стандартного

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]  # запуск скрипта для запуска миграции и сервера
    ports:
      - 9999:8000       # 8000 порт в контейнереб; 9999 портдля подключения к приложению
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: celery_app
    command: ["/fastapi_app/docker/celery.sh", "celery"]  # запуск скрипта для запуска celery
    depends_on:
      - redis

  flower:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: flower_app
    command: ["/fastapi_app/docker/celery.sh", "flower"]  # запуск скрипта для запуска celery
    depends_on:
      - redis
      - celery
    ports:
      - 8888:5555